
select * from customer

-- What is the total revenue generated by male versus female customers?
select gender, sum(purchase_amount) as revenue
from customer group by gender

-- Which customers used a discount but still they spent more than average purchase amount?
SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE
    discount_applied = 'Yes'
    AND purchase_amount > (
        SELECT AVG(purchase_amount) FROM customer
    );

-- What are the top five products with the highest average review rating?
SELECT
    item_purchased,
    ROUND(AVG(review_rating::NUMERIC), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

-- Compare the average purchase amount between standard and express shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--  Do subscribed customers spend more?
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, average_spend DESC;


--  Which five products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100)
        / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Segment customers into new, returning, and loyal based on their total number of previous purchases and show the count of each segment.'

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;




-- What are the top three most purchased products within each category?

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Are customers who are repeat buyers also likely to subscribe? 
-- (Repeat buyers are defined as customers who have more than five previous purchases.)

SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Check the revenue by age group.

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


-- Which K-Means cluster has the highest total customers?

SELECT cluster, COUNT(*) AS total_customers
FROM customer
GROUP BY cluster
ORDER BY total_customers DESC;

-- Which cluster generates the highest revenue?
SELECT cluster, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY cluster
ORDER BY total_revenue DESC;

-- What is the average purchase amount per cluster?
SELECT cluster, AVG(purchase_amount) AS avg_spend
FROM customer
GROUP BY cluster
ORDER BY cluster;

-- Which cluster buys most frequently (lowest purchase_frequency_days)?
SELECT cluster, AVG(purchase_of_fequancy_days) AS avg_days_between_purchases
FROM customer
GROUP BY cluster
ORDER BY avg_days_between_purchases ASC;


-- What is the gender distribution inside each cluster?
SELECT cluster, gender, COUNT(*) AS total
FROM customer
GROUP BY cluster, gender
ORDER BY cluster, gender;



-- Which age group is most active in each cluster?
SELECT cluster, age_group, COUNT(*) AS total
FROM customer
GROUP BY cluster, age_group
ORDER BY cluster, total DESC;


-- Do discount users belong to specific clusters?
SELECT cluster,
       COUNT(*) FILTER (WHERE discount_applied = 'Yes') AS discount_users,
       COUNT(*) AS total_customers,
       ROUND(
          COUNT(*) FILTER (WHERE discount_applied = 'Yes')::numeric 
          / COUNT(*) * 100, 2
       ) AS discount_usage_percent
FROM customer
GROUP BY cluster
ORDER BY discount_usage_percent DESC;


-- Which cluster gives the highest review ratings?

SELECT cluster, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY cluster
ORDER BY avg_rating DESC;

-- Does subscription status relate to cluster behavior?

SELECT cluster, subscription_status, COUNT(*) AS total
FROM customer
GROUP BY cluster, subscription_status
ORDER BY cluster, subscription_status;







































	